name: "[M] UTBot Java: build and run tests"

on:
  workflow_dispatch

jobs:
  utbot-analytics:
    runs-on: ubuntu-20.04
    container: unittestbot/java-env:java11-zulu-jdk-fx-gradle7.4.2-kotlinc1.7.0
    steps:
      - uses: actions/checkout@v2

      - name: Build and run test
        run: |
          cd utbot-analytics
          GRADLE_OPTS=-Dkotlin.compiler.execution.strategy=in-process gradle clean build --no-daemon
          
  utbot-api:
      runs-on: ubuntu-20.04
      container: unittestbot/java-env:java11-zulu-jdk-fx-gradle7.4.2-kotlinc1.7.0
      steps:
        - uses: actions/checkout@v2

        - name: Build and run test
          run: |
            cd utbot-api
            GRADLE_OPTS=-Dkotlin.compiler.execution.strategy=in-process gradle clean build --no-daemon
            
  utbot-cli:
      runs-on: ubuntu-20.04
      container: unittestbot/java-env:java11-zulu-jdk-fx-gradle7.4.2-kotlinc1.7.0
      steps:
        - uses: actions/checkout@v2

        - name: Build and run test
          run: |
            cd utbot-cli
            GRADLE_OPTS=-Dkotlin.compiler.execution.strategy=in-process gradle clean build --no-daemon
            
  utbot-core:
      runs-on: ubuntu-20.04
      container: unittestbot/java-env:java11-zulu-jdk-fx-gradle7.4.2-kotlinc1.7.0
      steps:
        - uses: actions/checkout@v2

        - name: Build and run test
          run: |
            cd utbot-core
            GRADLE_OPTS=-Dkotlin.compiler.execution.strategy=in-process gradle clean build --no-daemon
            
  utbot-framework-api:
      runs-on: ubuntu-20.04
      container: unittestbot/java-env:java11-zulu-jdk-fx-gradle7.4.2-kotlinc1.7.0
      steps:
        - uses: actions/checkout@v2

        - name: Build and run test
          run: |
            cd utbot-framework-api
            GRADLE_OPTS=-Dkotlin.compiler.execution.strategy=in-process gradle clean build --no-daemon
            
  utbot-framework:
      runs-on: ubuntu-20.04
      container: unittestbot/java-env:java11-zulu-jdk-fx-gradle7.4.2-kotlinc1.7.0
      steps:
        - uses: actions/checkout@v2

        - name: Build and run test
          run: |
            cd utbot-framework
            GRADLE_OPTS=-Dkotlin.compiler.execution.strategy=in-process gradle clean build --no-daemon
            
        - name: Upload utbot-framework logs
          if: ${{ always() }}
          uses: actions/upload-artifact@v2
          with:
            name: utbot_framework_logs
            path: utbot-framework/logs/*

        - name: Upload utbot-framework tests report artifacts if tests have failed
          if: ${{ failure() }}
          uses: actions/upload-artifact@v2
          with:
            name: utbot_framework_tests_report
            path: utbot-framework/build/reports/tests/test/*
            
        - name: Setup tmate session
          if: ${{ always() }}
          uses: mxschmitt/action-tmate@v3
          with:
            sudo: false
            
  utbot-fuzzers:
      runs-on: ubuntu-20.04
      container: unittestbot/java-env:java11-zulu-jdk-fx-gradle7.4.2-kotlinc1.7.0
      steps:
        - uses: actions/checkout@v2

        - name: Build and run test
          run: |
            cd utbot-fuzzers
            GRADLE_OPTS=-Dkotlin.compiler.execution.strategy=in-process gradle clean build --no-daemon
            
  utbot-gradle:
      runs-on: ubuntu-20.04
      container: unittestbot/java-env:java11-zulu-jdk-fx-gradle7.4.2-kotlinc1.7.0
      steps:
        - uses: actions/checkout@v2

        - name: Build and run test
          run: |
            cd utbot-gradle
            GRADLE_OPTS=-Dkotlin.compiler.execution.strategy=in-process gradle clean build --no-daemon
            
  utbot-instrumentation-tests:
      runs-on: ubuntu-20.04
      container: unittestbot/java-env:java11-zulu-jdk-fx-gradle7.4.2-kotlinc1.7.0
      steps:
        - uses: actions/checkout@v2

        - name: Build and run test
          run: |
            cd utbot-instrumentation-tests
            GRADLE_OPTS=-Dkotlin.compiler.execution.strategy=in-process gradle clean build --no-daemon
            
  utbot-instrumentation:
      runs-on: ubuntu-20.04
      container: unittestbot/java-env:java11-zulu-jdk-fx-gradle7.4.2-kotlinc1.7.0
      steps:
        - uses: actions/checkout@v2

        - name: Build and run test
          run: |
            cd utbot-instrumentation
            GRADLE_OPTS=-Dkotlin.compiler.execution.strategy=in-process gradle clean build --no-daemon
            
        - name: Upload utbot-instrumentation tests report artifacts if tests have failed
          if: ${{ failure() }}
          uses: actions/upload-artifact@v2
          with:
            name: utbot_instrumentation_tests_report
            path: utbot-instrumentation/build/reports/tests/test/*
            
  utbot-intellij:
      runs-on: ubuntu-20.04
      container: unittestbot/java-env:java11-zulu-jdk-fx-gradle7.4.2-kotlinc1.7.0
      steps:
        - uses: actions/checkout@v2

        - name: Build and run test
          run: |
            cd utbot-intellij
            GRADLE_OPTS=-Dkotlin.compiler.execution.strategy=in-process gradle clean build --no-daemon
            
            - name: Upload utbot-intellij tests report artifacts if tests have failed
            if: ${{ failure() }}
            uses: actions/upload-artifact@v2
            with:
              name: utbot_intellij_tests_report
              path: utbot-intellij/build/reports/tests/test/*
            
  utbot-junit-contest:
      runs-on: ubuntu-20.04
      container: unittestbot/java-env:java11-zulu-jdk-fx-gradle7.4.2-kotlinc1.7.0
      steps:
        - uses: actions/checkout@v2

        - name: Build and run test
          run: |
            cd utbot-junit-contest
            GRADLE_OPTS=-Dkotlin.compiler.execution.strategy=in-process gradle clean build --no-daemon
            
  utbot-maven:
      runs-on: ubuntu-20.04
      container: unittestbot/java-env:java11-zulu-jdk-fx-gradle7.4.2-kotlinc1.7.0
      steps:
        - uses: actions/checkout@v2

        - name: Build and run test
          run: |
            cd utbot-maven
            GRADLE_OPTS=-Dkotlin.compiler.execution.strategy=in-process gradle clean build --no-daemon
            
  utbot-sample:
      runs-on: ubuntu-20.04
      container: unittestbot/java-env:java11-zulu-jdk-fx-gradle7.4.2-kotlinc1.7.0
      steps:
        - uses: actions/checkout@v2

        - name: Build and run test
          run: |
            cd utbot-sample
            GRADLE_OPTS=-Dkotlin.compiler.execution.strategy=in-process gradle clean build --no-daemon
            
  utbot-summary-tests:
      runs-on: ubuntu-20.04
      container: unittestbot/java-env:java11-zulu-jdk-fx-gradle7.4.2-kotlinc1.7.0
      steps:
        - uses: actions/checkout@v2

        - name: Build and run test
          run: |
            cd utbot-summary-tests
            GRADLE_OPTS=-Dkotlin.compiler.execution.strategy=in-process gradle clean build --no-daemon
            
  utbot-summary:
      runs-on: ubuntu-20.04
      container: unittestbot/java-env:java11-zulu-jdk-fx-gradle7.4.2-kotlinc1.7.0
      steps:
        - uses: actions/checkout@v2

        - name: Build and run test
          run: |
            cd utbot-summary
            GRADLE_OPTS=-Dkotlin.compiler.execution.strategy=in-process gradle clean build --no-daemon
