name: "UTBot Java: build and run tests"

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  # Environment variable setting gradle options.
  GRADLE_OPTS: "-XX:MaxHeapSize=2048m -Dorg.gradle.jvmargs='-XX:MaxHeapSize=2048m -XX:MaxPermSize=512m -Dorg.gradle.daemon=false' -Dorg.gradle.daemon=false"

jobs:
  prepare-tests-matrix:
    runs-on: ubuntu-22.04
    # Outputs are used for passing data to dependent jobs.
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:        
      - name: Checkout repository
        uses: actions/checkout@v4

      - id: set-matrix
        name: Read and print config from framework-tests-matrix.json
        run: |
          TASKS=$(echo $(cat .github/workflows/framework-tests-matrix.json))
          echo "::set-output name=matrix::$TASKS"
          echo $TASKS

  framework:
    # This job does not need to wait for 'prepare-tests-matrix' result.
    # GitHub allocates runners portionally. Framework tests are time consuming. That's why we want to force them 
    # to start execution early.
    needs: prepare-tests-matrix
    # Using matrices let create multiple jobs runs based on the combinations of the variables from matrices. 
    # https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs
    strategy:
    # The option forces to execute all jobs even though some of them have failed.
      fail-fast: false
      matrix: ${{ fromJson(needs.prepare-tests-matrix.outputs.matrix) }}
    runs-on: ubuntu-22.04
    container: unittestbot/java-env:java11-zulu-jdk-fx-gradle7.4.2-kotlinc1.7.0
    steps:      
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run tests
      run: |     
        gradle --no-daemon :utbot-framework:test ${{ matrix.project.TESTS_TO_RUN }}

  project:
    needs: prepare-tests-matrix
    # Using matrices let create multiple jobs runs based on the combinations of the variables from matrices. 
    # https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs
    strategy:
    # The option forces to execute all jobs even though some of them have failed.
      fail-fast: false
      matrix:
        project: [utbot-api, utbot-cli, utbot-core, utbot-framework-api, utbot-fuzzers, utbot-gradle, utbot-instrumentation, utbot-instrumentation-tests, utbot-intellij, utbot-junit-contest, utbot-sample, utbot-summary, utbot-summary-tests]
    runs-on: ubuntu-22.04
    container: unittestbot/java-env:java11-zulu-jdk-fx-gradle7.4.2-kotlinc1.7.0
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run tests
      run: |
        cd ${{ matrix.project }}
        gradle build --no-daemon